#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfc72;
constexpr uint24_t FX_DATA_BYTES = 228771;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Images
{
  constexpr uint24_t PPOT = 0x000000;
  constexpr uint24_t Title = 0x003002;
  constexpr uint24_t HUD_Banana = 0x009004;
  constexpr uint24_t HUD_Time = 0x022A2E;
  constexpr uint24_t HUD_Directions = 0x026D38;
  constexpr uint24_t HUD_Health = 0x02721A;
  constexpr uint24_t Font_Alpha = 0x027F3C;
  constexpr uint24_t Font_Alpha_Big = 0x028AA2;
  constexpr uint24_t Font_Numbers = 0x029EE4;
  constexpr uint24_t HUD_TimesUp = 0x02A08A;
  constexpr uint24_t HUD_GameOver = 0x02A614;
  constexpr uint24_t Player = 0x02AADE;
  constexpr uint24_t Tree1 = 0x02B9E0;
  constexpr uint24_t Tree2 = 0x02BF3A;
  constexpr uint24_t Tree3 = 0x02C26C;
  constexpr uint24_t Tree4 = 0x02C4DE;
  constexpr uint24_t Tree5 = 0x02C768;
  constexpr uint24_t Tree6 = 0x02CA70;
  constexpr uint24_t Tree7 = 0x02CBDA;
  constexpr uint24_t Tree8 = 0x02CE40;
  constexpr uint24_t Foreground = 0x02CF98;
  constexpr uint24_t Background = 0x02E79A;
  constexpr uint24_t LowerOnly = 0x02ED9C;
  constexpr uint24_t UpperOnly = 0x02FC3E;
  constexpr uint24_t Both = 0x030E40;
  constexpr uint24_t Banana = 0x034A42;
  constexpr uint24_t Puff = 0x034B04;
  constexpr uint24_t Barrel = 0x035586;
  constexpr uint24_t Bird = 0x035888;
  constexpr uint24_t Spider = 0x035DCA;
  constexpr uint24_t Heart = 0x03648C;
  constexpr uint24_t Fire = 0x0364C4;
}

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x036946;
  constexpr uint24_t SFX_Death = 0x036DE0;
  constexpr uint24_t SFX_Victory = 0x036E84;
  constexpr uint24_t SFX_LandHard = 0x036F38;
  constexpr uint24_t SFX_PlayerBlip = 0x036F40;
  constexpr uint24_t SFX_EnemyBlip = 0x036F50;
  constexpr uint24_t SFX_PickUpItem = 0x036F60;
  constexpr uint24_t SFX_XPGain = 0x036F70;
  constexpr uint24_t SFX_Glint = 0x036F84;
  constexpr uint24_t Songs = 0x036F8C;
  constexpr uint24_t SFXs = 0x036F8F;
}

namespace Constants
{
  constexpr uint24_t StanceImgIdx = 0x036FA7;
  constexpr uint24_t StanceDetails = 0x0370EB;
  constexpr uint24_t Tree_X = 0x0375FB;
  constexpr uint24_t Font_Width = 0x03760B;
  constexpr uint24_t GameOver = 0x037625;
  constexpr uint24_t TimesUp = 0x0379B5;
  constexpr uint24_t BananaLaunch = 0x037D45;
}

namespace Images
{
  constexpr uint24_t TreeImages = 0x037D8B;
}

